services:
- name: service-1
  hostname: www.service1.com
  root: rootfs
  username: service1
  clockoffset: 0
  exec:
  - "!! ./main"
  mountpoints:
  - src: /tmp
    dst: /tmp
    mode: rw
  - src: /var/www/service1
    dst: /var/www/service1
    mode: rw
- name: service-2
  hostname: www.service2.com
  root: rootfs
  username: service2
  clockoffset: 0
  exec:
  - "!! ./main -servaddr 172.1.0.1"
  mountpoints:
  - src: /tmp
    dst: /tmp
    mode: rw
  - src: /var/www/service2
    dst: /var/www/service2
    mode: rw

networks:
- from: 
    name: service-1
    addr: 172.1.0.1/0
  to: 
    name: service-2
    addr: 172.1.0.2/0
